# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db155608654abee294064c61b3717388894e6d68def9e95638016b6dbab00da4095bd13f27c1615fd3df210490aa75869cd64f7328140a0666b126ac4384b3d4

test:
  secret_key_base: 84acc3720cc6d628990610f816a8eae5ed687ef88fbe394f05f87765b2bef2ac139182b8883f20112b091ec4f9af0986ace752fdc7f9b3a403d1db2f1e1d4e7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
